#!/usr/bin/env python3
"""Generate native OpenAI packaging and skill UI metadata from the Claude catalogue.

Use --check in CI. Generated files are committed; never maintain a second skill copy.
"""
from __future__ import annotations
import argparse
import json
from pathlib import Path
import sys
import yaml

ROOT = Path(__file__).resolve().parents[1]

def expected_files(root: Path = ROOT) -> dict[Path, str]:
    catalogue = json.loads((root / ".claude-plugin/marketplace.json").read_text())
    native = {"name": catalogue["name"], "plugins": []}
    files = {}
    for entry in catalogue["plugins"]:
        source = entry["source"]
        if not isinstance(source, str) or not source.startswith("./"):
            raise ValueError("this catalogue supports repository-local plugin sources only")
        directory = (root / source).resolve()
        if not directory.is_relative_to(root.resolve()):
            raise ValueError("plugin source escapes the repository")
        manifest = json.loads((directory / ".claude-plugin/plugin.json").read_text())
        portable = {k: manifest[k] for k in ("name", "version", "description", "author", "homepage", "repository", "license", "keywords", "skills") if k in manifest}
        files[directory / ".codex-plugin/plugin.json"] = json.dumps(portable, indent=2, ensure_ascii=False) + "\n"
        native["plugins"].append({"name": entry["name"], "source": {"source": "local", "path": source},
                                  "policy": {"installation": "AVAILABLE", "authentication": "ON_INSTALL"},
                                  "category": "Productivity"})
        for skill in sorted((directory / "skills").glob("*/SKILL.md")):
            metadata = yaml.safe_load(skill.read_text().split("---", 2)[1])
            name = metadata["name"]
            short = "Run the " + name.replace("-", " ") + " workflow"
            if len(short) > 64:
                short = short[:64].rsplit(" ", 1)[0]
            ui = {"interface": {"display_name": name.replace("-", " ").title(),
                                "short_description": short,
                                "default_prompt": "Use $" + name + " with the supplied context and evidence."}}
            files[skill.parent / "agents/openai.yaml"] = "# Generated by scripts/sync-openai.py; edit the skill metadata instead.\n" + yaml.safe_dump(ui, sort_keys=False, allow_unicode=True)
    files[root / ".agents/plugins/marketplace.json"] = json.dumps(native, indent=2, ensure_ascii=False) + "\n"
    return files

def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--check", action="store_true")
    a = p.parse_args()
    stale = []
    for path, content in expected_files().items():
        if not path.is_file() or path.read_text() != content:
            stale.append(path.relative_to(ROOT))
            if not a.check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content)
    if a.check and stale:
        print("Stale/missing OpenAI files: " + ", ".join(map(str, stale)), file=sys.stderr)
        return 1
    print(f"OpenAI metadata {'verified' if a.check else 'synchronised'}; {len(stale)} file(s) changed")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
